load("@com_nvidia_isaac_sdk//bzl:module.bzl", "isaac_cc_module")

isaac_cc_module(
    name = "pololu",
    visibility = ["//visibility:public"],
    deps = [
        "//genesis/pololu/components:pololu_driver",
        "//genesis/pololu/headcomp:pololu_head_driver"
    ]
)

